# Identificación del proyecto (Debe coincidir con lo que usas en el Makefile)
sonar.projectKey=apital_gains

# Rutas del código fuente (Solo queremos escanear el código, no los tests ni el venv)
sonar.sources=capital_gains

# ESTA ES LA LÍNEA MÁGICA PARA EL COVERAGE
sonar.python.coverage.reportPaths=coverage.xml

# Configuraciones extra para limpieza
sonar.python.version=3.9
sonar.sourceEncoding=UTF-8